### ISSUE TITLE
An explanation of how you will test the developed features of your system (in accordance with the tech stack chosen) as well as the method you will adopt to ensure continuous integration.

### ISSUE THREAD

**Issue by bigz4** [mashadchowdhury/GEMS-B#4]
Don't just use a technical term to describe the method; write a few sentences to explain the tools and techniques that will be involved. Read up on regression testing, and develop a feasiable plan that ensures when new code is added to your project that your project didn't break anything that was working before.

**Comment by msurkhi-1106** [comment]
Perfect ecvution
